"""empty message

Revision ID: 673a46eaf82a
Revises: 634749af1979
Create Date: 2023-06-22 14:33:15.550460

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '673a46eaf82a'
down_revision = '634749af1979'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('hashed_password', sa.String(length=255), nullable=False))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_column('hashed_password')

    # ### end Alembic commands ###